
class EstadoSolicitud:
    ABIERTA = "ABIERTA"
    OFERTANDO = "OFERTANDO"
    ACEPTADA = "ACEPTADA"
    EN_CURSO = "EN_CURSO"
    FINALIZADA = "FINALIZADA"
    CANCELADA = "CANCELADA"
    EXPIRADA = "EXPIRADA"

class EstadoOferta:
    PENDIENTE = "PENDIENTE"
    ACEPTADA = "ACEPTADA"
    RECHAZADA = "RECHAZADA"
    CANCELADA = "CANCELADA"


class EstadoDomiciliario:

    DISPONIBLE = "DISPONIBLE"

    EN_SERVICIO = "EN_SERVICIO"

    DESCONECTADO = "DESCONECTADO"

    SUSPENDIDO = "SUSPENDIDO"